name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - uses: actions/setup-node@v3

      - run: cargo install --git https://github.com/rustwasm/wasm-pack --tag v0.11.0

      - run: wasm-pack build --target nodejs
        env:
          RUST_BACKTRACE: 1

      - name: Upload Zip
        uses: actions/upload-artifact@v1
        with:
          name: toml_edit_wasm_pkg
          path: ./pkg

  test:
    name: Test
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v3
      - name: Download Linux amd64 tarball
        uses: actions/download-artifact@v2
        with:
          name: toml_edit_wasm_pkg
          path: pkg
      - run: node index.js
      - run: node check.js
